scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken # Ajoutez ce token
    email:
        digits: 6
        enabled: true
        sender_email: no-reply@cash.com
        sender_name: admin