security:
    # Configuration des hashers et des providers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                username_path: email
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour les routes 2FA
        # two_factor:
        #     pattern: ^/2fa
        #     stateless: true
        #     security: false  # Permet l'accès sans token JWT
        #     two_factor: ~

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            security: false

        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: /logout
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

    access_control:
        # Permettre l'accès à 2FA sans authentification
        - { path: ^/api/2fa, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/2fa_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/2fa(_check)?, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY  }
