services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_cash
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
      - /var/www/html/var
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: mysql://symfony_user:symfony_password@database:3306/symfony_cash
    networks:
      - app-network
      - mail-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mail-network
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
  mail-network:
    driver: bridge
