services:
  database:
    image: mysql:8.0
    container_name: my_db_cash
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_cash
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  mailer:
    image: schickling/mailcatcher
    container_name: my_mailer
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db_data:
